name: jmob
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.1+5

environment:
  sdk: ">=2.12.0 <3.0.0"


#  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  get: 4.6.3
  cupertino_icons: ^1.0.4
  get_storage: ^2.0.3
  loading_animations: ^2.2.0
  intl_phone_number_input: ^0.7.0+2
  pin_code_fields: ^7.4.0
  slide_countdown: ^0.2.3
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.6.1
  carousel_slider: ^4.1.1
  flutter_widget_from_html_core: ^0.8.5+1
  intl: ^0.17.0
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.0
  dio: ^4.0.6
  flutter_local_notifications: ^9.4.1
  webview_flutter: 3.0.2
  adaptive_dialog: ^1.5.0+1
  cached_network_image: ^3.2.0
  skeleton_text: ^3.0.0
  collection: ^1.15.0
  card_swiper : ^2.0.1
  google_fonts: ^2.3.2
  restart_app: ^1.1.0+1
  firebase_app_check: ^0.0.6+13
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  firebase_messaging: ^11.4.0
  cloud_firestore: ^3.1.15
  firebase_auth: ^3.3.18

  woocommerce:
    path: ./plugins/woocommerce



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true